#!/bin/bash
set -e -x
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade
apt-get install git -y
cd /home/ubuntu
git clone https://github.com/Steve525/cs462.git
chmod a+x cs462/bootstrap
./cs462/bootstrap